DELETE FROM exercises;

INSERT INTO exercises
(id,name_zh,name_en,muscle_group,secondary_muscles,equipment_key,difficulty,movement_type,poster_url,video_url,animation_type,instructions_zh,instructions_en,mistakes_zh,mistakes_en,active)
VALUES
('bench-press','杠铃卧推','Barbell Bench Press','chest','triceps','barbell','intermediate','push','https://wger.de/media/exercise-images/192/Bench-press-1.png','https://wger.de/media/exercise-video/73/2bdb390c-312c-4497-a722-5eed2c823e5a.MOV','video','肩胛后收并稳定贴住凳面|杠铃下降到下胸位置|双脚踩稳后沿原轨迹推起','Set the shoulder blades against the bench|Lower the bar to the lower chest|Drive back up with feet planted','手腕后折|肘部完全外展|臀部离开凳面','Bent wrists|Elbows fully flared|Hips leaving the bench',1),
('db-bench','哑铃卧推','Dumbbell Bench Press','chest','triceps','dumbbell','beginner','push','https://wger.de/media/exercise-images/97/Dumbbell-bench-press-1.png','https://wger.de/media/exercise-video/75/080c799b-8afd-4130-8d72-9cef0cd79f54.MOV','video','哑铃位于胸部两侧|前臂保持接近垂直|向上推起后控制下放','Start with dumbbells beside the chest|Keep forearms close to vertical|Press up and lower under control','哑铃碰撞|肩部前顶|下放过快','Clashing dumbbells|Shoulders rolling forward|Dropping too fast',1),
('incline-db-press','上斜哑铃卧推','Incline Dumbbell Press','chest','shoulders','dumbbell','beginner','push','https://wger.de/media/exercise-images/16/Incline-press-1.png','https://wger.de/media/exercise-video/537/b9c937e9-daeb-42a9-be8e-7a77e368478c.MOV','video','凳面调整到约30度|哑铃落在上胸两侧|沿略向内的轨迹推起','Set the bench near 30 degrees|Lower beside the upper chest|Press slightly inward','凳面角度过高|肩部前移|手腕失去中立','Bench too steep|Shoulders moving forward|Bent wrists',1),
('seated-row','窄握坐姿划船','Seated Cable Row','back','biceps','cable','beginner','pull','https://wger.de/media/exercise-images/512/b938437e-ff00-4679-9036-acb41bb28bbd.png','https://wger.de/media/exercise-video/512/fff4c294-93f0-4926-b3a2-bf59ad4afaa5.MOV','video','胸口抬起并保持核心稳定|把手拉向腹部|肩胛后收后控制前伸','Keep the chest tall|Pull the handle to the abdomen|Control the forward reach','含胸|后仰借力|配重片撞击','Rounding the back|Leaning back|Slamming the stack',1),
('pull-up','引体向上','Pull-up','back','biceps','pull-up-bar','intermediate','pull','https://wger.de/media/exercise-images/475/b0554016-16fd-4dbe-be47-a2a17d16ae0e.jpg','https://wger.de/media/exercise-video/475/83067ffe-ccb9-4e22-8507-5131b211ce74.MOV','video','先下沉肩胛再开始拉起|胸口朝向横杆|控制下降到接近伸直','Depress the shoulder blades first|Lead the chest toward the bar|Lower under control','大幅摆动|耸肩|下降失控','Excessive swinging|Shrugging|Uncontrolled lowering',1),
('rear-delt-raise','俯身侧平举','Bent-over Lateral Raise','shoulders','back','dumbbell','intermediate','isolation','assets/ex-rear-delt.jpg','https://wger.de/media/exercise-video/82/28b53647-27e7-47cf-8852-2ee666c8b628.MOV','video','髋部折叠并保持背部平直|手臂微屈向两侧展开|肩胛稳定且不耸肩','Hinge with a flat back|Raise with soft elbows|Keep the shoulders down','重量过大|身体摆动|手臂抬得过高','Too much weight|Body swing|Raising too high',1),
('face-pull','绳索面拉','Cable Face Pull','shoulders','back','cable','beginner','pull','assets/ex-seated-row.jpg','https://wger.de/media/exercise-video/222/eea93fcc-6a3c-4783-8f70-0234c791a001.MOV','video','滑轮调至面部高度|绳索拉向眉毛两侧|肘部抬起并完成外旋','Set the cable at face height|Pull toward the eyebrows|Keep elbows high and rotate out','腰部后仰|耸肩|重量过大','Leaning back|Shrugging|Too much weight',1),
('db-shoulder-press','哑铃肩推','Dumbbell Shoulder Press','shoulders','triceps','dumbbell','beginner','push','https://wger.de/media/exercise-images/123/dumbbell-shoulder-press-large-1.png','https://wger.de/media/exercise-video/567/64f33c19-1d96-4b7c-af17-6c6a4941c614.MOV','video','核心收紧并保持肋骨下沉|哑铃从耳朵两侧推起|顶端不过度锁死肘关节','Brace and keep the ribs down|Press from beside the ears|Avoid hard elbow lockout','腰部过伸|手腕后折|下降幅度不足','Overarching the back|Bent wrists|Short range',1),
('front-squat','杠铃前蹲','Barbell Front Squat','legs','core','barbell','intermediate','squat','https://wger.de/media/exercise-images/191/Front-squat-1-857x1024.png','https://wger.de/media/exercise-video/257/93145935-29db-4e52-9d2d-174b1c30c098.MOV','video','肘部抬高固定杠铃|膝盖沿脚尖方向移动|保持躯干直立站起','Keep elbows high to secure the bar|Track knees over toes|Stand with an upright torso','肘部下沉|脚跟抬起|膝盖内扣','Dropping elbows|Heels lifting|Knees collapsing',1),
('leg-press','腿举','Leg Press','legs','glutes','leg-press','beginner','press','https://wger.de/media/exercise-images/371/d2136f96-3a43-4d4c-9944-1919c4ca1ce1.webp','https://wger.de/media/exercise-video/371/6aae16b4-01b9-4eb4-935c-3250f84d2c59.MOV','video','腰背贴紧靠垫|膝盖沿脚尖方向弯曲|推起时保留轻微屈膝','Keep the back against the pad|Track knees over toes|Keep a soft knee at the top','腰部离开靠垫|膝盖内扣|完全锁死膝盖','Back lifting off the pad|Knees collapsing|Hard knee lockout',1),
('romanian-deadlift','罗马尼亚硬拉','Romanian Deadlift','legs','glutes','barbell','intermediate','hinge','assets/plan-legs.jpg','https://wger.de/media/exercise-video/507/307e7276-a14d-4ea0-b579-f5b0dbc6f5af.MOV','video','膝盖保持轻微弯曲|髋部向后移动让杠铃贴腿下降|臀腿后侧拉伸后伸髋站起','Keep a soft knee bend|Push hips back with the bar close|Extend the hips after the hamstring stretch','腰背弯曲|杠铃远离身体|下蹲替代髋铰链','Rounding the back|Bar drifting forward|Turning it into a squat',1),
('hip-thrust','杠铃臀推','Barbell Hip Thrust','glutes','legs','barbell','beginner','hinge','assets/plan-legs.jpg','https://wger.de/media/exercise-video/294/45bacf4b-1bb6-4d47-8bd1-9f00eddd4019.MOV','video','肩胛下缘支撑在凳面|下巴微收并保持肋骨下沉|伸髋到躯干与大腿接近一线','Support the lower shoulder blades on the bench|Tuck the chin and keep ribs down|Extend until torso and thighs align','腰椎过伸|双脚位置过远|顶端没有收紧臀部','Overextending the back|Feet too far away|No glute squeeze',1);
